---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
  - package-ecosystem: "docker"
    directory: "/xteve"
    schedule:
      interval: daily
      time: "06:00"
